println(" _____ ");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |                                                                                                                      ");
println(" |   |                                _____                                           _____");
println(" |   |                              (<o> <o>)                                       (<o> <o>)");
println(" |   |                                 | |                                             | |");
println(" |   |                             o--<| |>--o                                     o--<| |>--o");
println(" |   |                                 | |                                             | |");
println(" |   |                                /  \\                                            /  \\                              ");
println(" |   |                               --   --                                        --    --                               ");
println(" |    ---------------------------------------------------------------------------------------------------------------------------------|"); 
println(" |    _________________________________________________________________________________________________________________________________|");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |                                                                                                                      ");
println(" |   |                                _____                                           _____");
println(" |   |                              (<o> <o>)                                      (<o> <o>)");
println(" |   |                                 | |                                            | |");
println(" |   |                             o--<| |>--o                                    o--<| |>--o");
println(" |   |                                 | |                                            | |");
println(" |   |                                /  \\                                           /  \\                              ");
println(" |   |                               --   --                                       --    --                               ");
println(" |    --------------------------------------------------------------------------------------------|");
println(" |    ____________________________________________________________________________________________|");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |                                                                                                                      ");
println(" |   |                                  _____                                           _____");
println(" |   |                                (<o> <o>)                                       (<o> <o>)");
println(" |   |                                   | |                                             | |");
println(" |   |                               o--<| |>--o                                     o--<| |>--o");
println(" |   |                                   | |                                             | |");
println(" |   |                                  /  \\                                            /  \\                              ");
println(" |   |                                 --   --                                        --    --                               ");
println(" |    ---------------------------------------------------------------------------------------------------------------------------------|");
println(" |    _________________________________________________________________________________________________________________________________|");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |                                                                                                                      ");
println(" |   |                                _____                                           _____");
println(" |   |                              (<o> <o>)                                       (<o> <o>)");
println(" |   |                                 | |                                             | |");
println(" |   |                             o--<| |>--o                                     o--<| |>--o");
println(" |   |                                 | |                                             | |");
println(" |   |                                /  \\                                            /  \\                              ");
println(" |   |                               --   --                                        --    --                               ");
println(" |    ---------------------------------------------------------------------------------------------------------------------------------|"); 
println(" |    _________________________________________________________________________________________________________________________________|");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |                                                                                                                      ");
println(" |   |                                _____                                           _____");
println(" |   |                              (<o> <o>)                                      (<o> <o>)");
println(" |   |                                 | |                                            | |");
println(" |   |                             o--<| |>--o                                    o--<| |>--o");
println(" |   |                                 | |                                            | |");
println(" |   |                                /  \\                                           /  \\                              ");
println(" |   |                               --   --                                       --    --                               ");
println(" |    --------------------------------------------------------------------------------------------|");
println(" |    ____________________________________________________________________________________________|");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |                                                                                                                      ");
println(" |   |                                  _____                                           _____");
println(" |   |                                (<o> <o>)                                       (<o> <o>)");
println(" |   |                                   | |                                             | |");
println(" |   |                               o--<| |>--o                                     o--<| |>--o");
println(" |   |                                   | |                                             | |");
println(" |   |                                  /  \\                                            /  \\                              ");
println(" |   |                                 --   --                                        --    --                               ");
println(" |    ---------------------------------------------------------------------------------------------------------------------------------|");
println(" |    _________________________________________________________________________________________________________________________________|");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |                                                                                                                      ");
println(" |   |                                _____                                           _____");
println(" |   |                              (<o> <o>)                                       (<o> <o>)");
println(" |   |                                 | |                                             | |");
println(" |   |                             o--<| |>--o                                     o--<| |>--o");
println(" |   |                                 | |                                             | |");
println(" |   |                                /  \\                                            /  \\                              ");
println(" |   |                               --   --                                        --    --                               ");
println(" |    ---------------------------------------------------------------------------------------------------------------------------------|"); 
println(" |    _________________________________________________________________________________________________________________________________|");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |                                                                                                                      ");
println(" |   |                                _____                                           _____");
println(" |   |                              (<o> <o>)                                      (<o> <o>)");
println(" |   |                                 | |                                            | |");
println(" |   |                             o--<| |>--o                                    o--<| |>--o");
println(" |   |                                 | |                                            | |");
println(" |   |                                /  \\                                           /  \\                              ");
println(" |   |                               --   --                                       --    --                               ");
println(" |    --------------------------------------------------------------------------------------------|");
println(" |    ____________________________________________________________________________________________|");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |                                                                                                                      ");
println(" |   |                                  _____                                           _____");
println(" |   |                                (<o> <o>)                                       (<o> <o>)");
println(" |   |                                   | |                                             | |");
println(" |   |                               o--<| |>--o                                     o--<| |>--o");
println(" |   |                                   | |                                             | |");
println(" |   |                                  /  \\                                            /  \\                              ");
println(" |   |                                 --   --                                        --    --                               ");
println(" |    ---------------------------------------------------------------------------------------------------------------------------------|");
println(" |    _________________________________________________________________________________________________________________________________|");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" |   |");
println(" | H |");
println(" | A |");
println(" | T |");
println("_______ ");
println("__   __");
println("<O> <O>");
println("(=====)");
